# -*- coding: utf-8 -*-
"""
/***************************************************************************
 RasterVolumeCompare
                                 A QGIS plugin
 Calculates the difference in volume between two raster layers
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-01-16
        copyright            : (C) 2023 by L Yang/Bligh Tanner
        email                : lauren.yang@blightanner.com.au
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load RasterVolumeCompare class from file RasterVolumeCompare.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .raster_volume_compare import RasterVolumeCompare
    return RasterVolumeCompare(iface)
